### PR TITLE
Updated Sebastian's profile

### PR DESCRIPTION
**Pull request by sebastianzur**

### CODE REVIEW

**Review by cschaffner — COMMENTED** [review]
Thanks for the pull request, Sebastian. The lock file should not be committed.

**Comment by sebastianzur** [comment]
Aah my bad sorry, should I do a new pull request without the lock file?

**Comment by cschaffner** [comment]
I think you can adjust it and submit again

**Review by cschaffner — APPROVED** [review]
looks good now!

**Pull request merged**
